version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pokett-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - "27017:27017"
    volumes:
      - ./.mongodb:/data/db
    restart: unless-stopped
    command: mongod --bind_ip_all

volumes:
  mongodb_data:
    driver: local 